"use client";

import { AlertTriangle, CheckCircle2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useMemo, useState } from "react";
import { parseEther } from "viem";
import { ProtocolFooter } from "@/components/truthbond/protocol-footer";
import { ProtocolHeader } from "@/components/truthbond/protocol-header";
import { TransactionPanel } from "@/components/truthbond/transaction-panel";
import { useTruthBondTransaction } from "@/components/truthbond/use-truthbond-transaction";

export default function CreateClaimPage() {
  const router = useRouter(); const { state, execute } = useTruthBondTransaction();
  const [claimId, setClaimId] = useState(""); const [claimText, setClaimText] = useState(""); const [criteria, setCriteria] = useState(""); const [bond, setBond] = useState("1"); const [challengeHours, setChallengeHours] = useState("24"); const [resolutionHours, setResolutionHours] = useState("72");
  const objective = useMemo(() => claimText.trim().length >= 20 && criteria.trim().length >= 20, [claimText, criteria]);
  async function submit(event: FormEvent) { event.preventDefault(); const now=Math.floor(Date.now()/1000); const challenge=now+Number(challengeHours)*3600; const resolution=now+Number(resolutionHours)*3600; const result=await execute({functionName:"create_claim",args:[claimId.trim(),claimText.trim(),criteria.trim(),challenge,resolution],value:parseEther(bond),label:"Claim creation"}); if(result) setTimeout(()=>router.push(`/claims/${claimId.trim()}`),1000); }
  return <><ProtocolHeader/><main className="page-shell"><div className="page-intro"><span className="kicker">NEW ASSERTION</span><h1>Put a verifiable fact on the line.</h1><p>State one objective claim, define how validators should verify it, and lock a creator bond.</p></div><div className="form-layout"><form className="protocol-form" onSubmit={submit}><label>Claim ID<span>Short, unique, URL-safe identifier</span><input required minLength={4} pattern="[a-z0-9-]+" value={claimId} onChange={e=>setClaimId(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="dencun-mainnet-date"/></label><label>Factual claim<span>One specific statement with a testable answer</span><textarea required minLength={20} value={claimText} onChange={e=>setClaimText(e.target.value)} placeholder="Ethereum's Dencun upgrade activated on mainnet on March 13, 2024."/></label><label>Resolution criteria<span>Tell validators which evidence and conditions count</span><textarea required minLength={20} value={criteria} onChange={e=>setCriteria(e.target.value)} placeholder="Confirm with at least two independent reliable public sources..."/></label><div className="field-grid"><label>Creator bond (GEN)<input required type="number" min="0.001" step="0.001" value={bond} onChange={e=>setBond(e.target.value)}/></label><label>Challenge window (hours)<input required type="number" min="1" value={challengeHours} onChange={e=>setChallengeHours(e.target.value)}/></label><label>Resolution window (hours)<input required type="number" min="2" value={resolutionHours} onChange={e=>setResolutionHours(e.target.value)}/></label></div><button className="button button-primary button-wide" disabled={!objective || state.phase==="consensus" || state.phase==="wallet"}>Create claim & lock {bond || "0"} GEN</button><TransactionPanel state={state}/></form><aside className="guidance-card"><h2>Evidence standard</h2><ul><li><CheckCircle2/>Publicly verifiable and time-bounded</li><li><CheckCircle2/>Specific enough for a clear verdict</li><li><CheckCircle2/>Resolvable from reliable independent sources</li><li><AlertTriangle/>Not opinion, prediction, or private information</li></ul><p>Web content is treated only as untrusted factual evidence. It cannot alter the adjudication rules or direct transfers.</p></aside></div></main><ProtocolFooter/></>;
}
